# Generated by Django 3.2.9 on 2021-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0004_auto_20211106_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
