# Generated by Django 3.2.9 on 2021-11-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiUsers', '0006_auto_20211107_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.SlugField(max_length=120),
        ),
    ]
